language: php

php:
    - 5.4
    - 5.5
    - 5.6

# faster builds on new travis setup not using sudo
sudo: false

git:
  submodules: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

# script run before anything
before_script:
    - composer global require "fxp/composer-asset-plugin:~1.0.0"
    - composer install
    - cp phpunit.xml.dist phpunit.xml

install:
    - travis_retry composer self-update && composer --version


script:
    phpunit --configuration phpunit.xml
