language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

# faster builds on new travis setup not using sudo
sudo: false

git:
  submodules: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

# script run before anything
before_script:
    - cp phpunit.xml.dist phpunit.xml

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer global require "fxp/composer-asset-plugin:^1.4.1"
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry composer install --prefer-dist --no-interaction

script:
    - phpunit --verbose $PHPUNIT_FLAGS
